# Generated by Django 3.2.12 on 2022-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='black',
            field=models.BooleanField(default=1),
        ),
    ]
