# Generated by Django 3.2.12 on 2022-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_video_black'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='black',
            field=models.BooleanField(default=0),
        ),
    ]
