# Generated by Django 3.2.12 on 2022-06-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='guard_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='skill_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
